pipeline:
  identifier: Build_couman05_azure_devops_octane_tests_1773056041662
  name: Build azure-devops-octane-tests
  orgIdentifier: default
  projectIdentifier: default_project
  variables:
    - name: static_message
      type: String
      value: Hello from static pipeline variable
    - name: runtime_message
      type: String
      value: <+input>.default("Hello").allowedValues("Hello","Hi","Greetings")
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1773055927224
        repoName: couman05/azure-devops-octane-tests
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo hello world
                  spec:
                    shell: Sh
                    command: echo "Hello from Harness CI"
                  timeout: ""
                  type: Run
                  description: Example Run Step
              - step:
                  type: Run
                  name: echo test pipeline
                  identifier: echo_test_pipeline
                  spec:
                    shell: Sh
                    command: echo "test pipeline"
              - step:
                  type: Run
                  name: Print Account Variable
                  identifier: print_account_variable
                  spec:
                    shell: Sh
                    command: "echo \"Account variable value: <+variable.account.dummy_variable>\""
              - step:
                  type: Run
                  name: Print Pipeline Variables
                  identifier: print_pipeline_variables
                  spec:
                    shell: Sh
                    command: |
                      echo "Static variable: <+pipeline.variables.static_message>"
                      echo "Runtime variable: <+pipeline.variables.runtime_message>"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
        description: ""
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: Ignore
    - stage:
        name: second_build
        identifier: second_build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run Maven tests
                  identifier: Run_Maven_tests
                  spec:
                    shell: Sh
                    command: mvn test
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - target/surefire-reports/*.xml
                  failureStrategies:
                    - onFailure:
                        errors:
                          - AllErrors
                        action:
                          type: Ignore
                contextType: Pipeline
              - step:
                  type: GCSUpload
                  name: upload to gcs
                  identifier: upload_to_gcs
                  spec:
                    connectorRef: account.gcp_connector
                    bucket: harness-second-bucket
                    sourcePath: target/surefire-reports/*.xml
                contextType: Pipeline
              - step:
                  type: Plugin
                  name: publish artifact url
                  identifier: publish_artifact_url
                  spec:
                    connectorRef: account.harnessImage
                    image: plugins/artifact-metadata-publisher
                  description: Publish Artifact URL to Harness Artifacts Tab
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  notificationRules:
    - name: notification_rule
      identifier: notification_rule
      pipelineEvents:
        - type: AllEvents
      notificationMethod:
        type: Webhook
        spec:
          webhookUrl: https://smee.io/RfmUmlsKaxzk7Lh
          headers:
            ALM-OCTANE-TECH-PREVIEW: "true"
            Authorization: Bearer ew0KICAidmVyc2lvbiIgOiAiYnR2MSINCn0%3D.V1%3AZTmLrlJDKumPirYWyU4D4TKnlAIAqnO3N0BadIrN%2BzekOEBHbgMr4lPNkc43yvPzah6xVt%2FPMC2X9e1eH7rLUCFkF0S7HokJfV1yeq4Re%2FjdYu%2BsLmpA2L74v%2BOsd0WZzMVm80suq%2FTR5ZDX%2FciniP8osotknJf5Wpv34YNmwCsKCFT0C%2BG%2Bu5s%2BFh4BHqDlRzMLVmYEWYQnyKvt2U7zXZtMPqx%2F2MZw45bbiIahcO%2FE6asC8rV%2FED%2FOygKy8D78uDEh7CYDEgxpnqfCMABRY5UzoIb7%2Fzltfejy0BK74QrqnA9iw6BfSwNIIHjUhOY0c8vN%2FYbEJJUWJT1jCEETNxdUGMCzA3XGQH5fz2aqrf1LSncZqR8r7ixmxgSXL7gN148%2BMs6GN3gns4WjzWs0JfuEvaLdRpLRFyxDE760BHbPQVYEes080I640eU%3D
      enabled: true
