pipeline:
  identifier: Build_couman05_azure_devops_octane_tests_1773056041662
  name: Build azure-devops-octane-tests
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1773055927224
        repoName: couman05/azure-devops-octane-tests
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo hello world
                  spec:
                    shell: Sh
                    command: echo "Hello from Harness CI"
                  timeout: ""
                  type: Run
                  description: Example Run Step
              - step:
                  type: Run
                  name: echo test pipeline
                  identifier: echo_test_pipeline
                  spec:
                    shell: Sh
                    command: echo "test pipeline"
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
