pipeline:
  identifier: Build_couman05_azure_devops_octane_tests_1773056041662
  name: Build azure-devops-octane-tests
  orgIdentifier: default
  projectIdentifier: default_project
  variables:
    - name: static_message
      type: String
      value: Hello from static pipeline variable
    - name: runtime_message
      type: String
      value: <+input>.default("Hello").allowedValues("Hello","Hi","Greetings")
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1773055927224
        repoName: couman05/azure-devops-octane-tests
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo hello world
                  spec:
                    shell: Sh
                    command: echo "Hello from Harness CI"
                  timeout: ""
                  type: Run
                  description: Example Run Step
              - step:
                  type: Run
                  name: echo test pipeline
                  identifier: echo_test_pipeline
                  spec:
                    shell: Sh
                    command: echo "test pipeline"
              - step:
                  type: Run
                  name: Print Account Variable
                  identifier: print_account_variable
                  spec:
                    shell: Sh
                    command: "echo \"Account variable value: <+variable.account.dummy_variable>\""
              - step:
                  type: Run
                  name: Print Pipeline Variables
                  identifier: print_pipeline_variables
                  spec:
                    shell: Sh
                    command: |
                      echo "Static variable: <+pipeline.variables.static_message>"
                      echo "Runtime variable: <+pipeline.variables.runtime_message>"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
        description: ""
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: Ignore
    - stage:
        name: second_build
        identifier: second_build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run Maven tests
                  identifier: Run_Maven_tests
                  spec:
                    shell: Sh
                    command: mvn test
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - target/surefire-reports/*.xml
                contextType: Pipeline
              - step:
                  type: GCSUpload
                  name: upload to gcs
                  identifier: upload_to_gcs
                  spec:
                    connectorRef: account.gcp_connector
                    bucket: harness-second-bucket
                    sourcePath: target/surefire-reports/*.xml
                contextType: Pipeline
              - step:
                  type: Plugin
                  name: publish artifact url
                  identifier: publish_artifact_url
                  spec:
                    connectorRef: account.harnessImage
                    image: plugins/artifact-metadata-publisher
                  description: Publish Artifact URL to Harness Artifacts Tab
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  notificationRules:
    - name: notification_rule
      identifier: notification_rule
      pipelineEvents:
        - type: AllEvents
      notificationMethod:
        type: Webhook
        spec:
          webhookUrl: https://smee.io/RfmUmlsKaxzk7Lh
          headers:
            ALM-OCTANE-TECH-PREVIEW: "true"
            Authorization: Bearer ew0KICAidmVyc2lvbiIgOiAiYnR2MSINCn0%3D.V1%3Ax2tjE5pShhz68KZESFbnmRUnloQV%2Fa4MPu35giud0msX%2Be9xkmlL%2FGhtMI1ep3pKlDSit57FwPduEX8M%2Fz9L8JwPCWVv1%2FUq8zj92Emh0XJ3te%2Fd8vRKDp6w3mi8%2FTdD9TuTlnhVQi2ebTaAtmD5oJLMBIfxtS93QQpzAugqqFzagnSWt6zcRVWVnnnuLsNMtNB%2B8lSDvYMBo9p4DJzfMfM8lmhn3ml45GPWwEnSvSpj8M6P7K4lhFtL9rIr3efh37s3fkXz5AJLPhBHETvtT6CVk%2BnhUBDIfrUifOTjwlsThpEpJlGGTE3U4u24wlCjn9AAoWywfhSiY6sAM0bQfJamhK0GHMdtqgbUieVjSraN%2F%2F9sC8H6BJsB4sXayaOYjEHIlywHq3%2FBPHzgfS4ze8XOS46dcFkILCOI%2FnDIx4%2BID2JHyF7JuQ%3D%3D
      enabled: true
